# Generated by Django 4.2.8 on 2026-04-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_admin_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedfile',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
